// Command genvectors regenerates testdata/vectors.json.
//
// Run it only when the wire format changes on purpose:
//
//	go run ./internal/genvectors > testdata/vectors.json
//
// Regenerating to make a failing test pass is exactly the mistake the vectors
// exist to catch — every published attestation is signed over these bytes.
package main

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/cleatonxyz/attestly"
)

func main() {
	seed := []byte(strings.Repeat("\x01", ed25519.SeedSize))
	priv := ed25519.NewKeyFromSeed(seed)
	pub := priv.Public().(ed25519.PublicKey)

	claims := []struct {
		name  string
		claim attestly.Claim
	}{
		{"horizon", horizonClaim()},
		{"minimal", minimalClaim()},
		{"nested", nestedClaim()},
	}

	out := map[string]any{
		"_comment":       "Generated by internal/genvectors. Test key only: seed is 32 bytes of 0x01. Never use it for anything.",
		"domain":         attestly.Domain,
		"alg":            attestly.AlgEd25519,
		"seed_hex":       hex.EncodeToString(seed),
		"public_key_hex": hex.EncodeToString(pub),
	}

	cases := make([]map[string]string, 0, len(claims))
	for _, c := range claims {
		canonical, err := c.claim.Canonical()
		check(err)
		digest, err := c.claim.Digest()
		check(err)
		att, err := attestly.Sign(priv, attestly.KeyIDFor(pub), c.claim)
		check(err)
		cases = append(cases, map[string]string{
			"name":       c.name,
			"canonical":  string(canonical),
			"digest_hex": hex.EncodeToString(digest[:]),
			"sig_b64":    base64.StdEncoding.EncodeToString(att.Sig),
		})
	}
	out["cases"] = cases

	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	check(enc.Encode(out))
}

func horizonClaim() attestly.Claim {
	return attestly.Claim{
		Subject: "base:0x1f98431c8ad98523631ae4a59f267346ea31f984",
		Schema:  "cleaton.horizon/v1",
		Payload: map[string]any{
			"horizon_days": int64(9),
			"confidence":   "0.70",
			"model":        "ensemble-a",
		},
		IssuedAt:  time.Unix(1_755_000_000, 0).UTC(),
		ExpiresAt: time.Unix(1_755_086_400, 0).UTC(),
	}
}

func minimalClaim() attestly.Claim {
	return attestly.Claim{
		Subject:   "base:0xdead",
		Schema:    "cleaton.horizon/v1",
		IssuedAt:  time.Unix(1_755_000_000, 0).UTC(),
		ExpiresAt: time.Unix(1_755_003_600, 0).UTC(),
	}
}

func nestedClaim() attestly.Claim {
	return attestly.Claim{
		Subject: "arbitrum:0xbeef",
		Schema:  "cleaton.portfolio/v1",
		Payload: map[string]any{
			"positions": []any{
				map[string]any{"pool": "0xaaa", "horizon_days": int64(3)},
				map[string]any{"pool": "0xbbb", "horizon_days": int64(21)},
			},
			"unicode": "héllo\n\"quoted\"",
			"empty":   nil,
			"flag":    true,
		},
		IssuedAt:  time.Unix(1_755_000_000, 0).UTC(),
		ExpiresAt: time.Unix(1_755_086_400, 0).UTC(),
		Nonce:     "n-1",
	}
}

func check(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "genvectors:", err)
		os.Exit(1)
	}
}
